name: dbptk-desktop # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.8.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Relational Database Viewer for databases based on SIARD 2
description: |
  Relational databases are one of the most important technologies supporting today’s information management activities. They are designed to store, organize and explore digital records that not only support but also document day-to-day business operations. Very often, these records are irreplaceable or prohibitively expensive to reacquire by other means rendering the preservation of databases a serious concern.
  The Database Preservation Toolkit is a Desktop tool that allows conversion between Database formats, including connection to live systems, for purposes of digitally preserving databases. The toolkit allows conversion of live or backed-up databases into preservation formats such as SIARD, a XML-based format created for the purpose of database preservation. The toolkit also allows conversion of the preservation formats back into live systems to allow the full functionality of databases.
  The Database Preservation Toolkit is also a lightweight viewer for relational databases, specially if preserved in SIARD 2, that uses Apache Solr as a backend, and allows browsing, search, and export.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
