#name: Deploy
#
#on: 
#  repository_dispatch: 
#    types: ["dispatch-main"]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Setup Node.js 10
#        uses: actions/setup-node@v2
#        with:
#          node-version: '10'
#
#      - name: Update package.json
#        run: |
#          cat package.json | jq ".version = \"$RELEASE_VERSION\"" | jq ".dbvtkVersion = \"$RELEASE_VERSION\"" > tmp
#          mv tmp package.json
#        env:
#          RELEASE_VERSION: ${{ github.event.client_payload.version }}
#
#      - name: Package MacOS
#        if: startsWith(matrix.os, 'macos')
#        run: yarn --pure-lockfile && yarn dist
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          DBPTK_UI_VERSION: ${{ github.event.client_payload.version }}
#          FLOW: main
#
#      - name: Package Linux & Windows
#        if: startsWith(matrix.os, 'ubuntu')
#        run: |
#          docker run --rm \
#            --env FLOW="${FLOW}" \
#            --env GITHUB_TOKEN="${GITHUB_TOKEN}" \
#            --env DBPTK_UI_VERSION="${DBPTK_UI_VERSION}" \
#            -v ${PWD}:/project \
#            -v ~/.cache/electron:/root/.cache/electron \
#            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
#            electronuserland/builder:wine \
#            /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn dist-lw"
#        env:
#          DBPTK_UI_VERSION: ${{ steps.tag.outputs.result }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          FLOW: ${{ github.event.client_payload.flow }}
#      
#      - name: Install Snapcraft
#        if: startsWith(matrix.os, 'ubuntu')
#        uses: samuelmeuli/action-snapcraft@v1
#        with:
#          snapcraft_token: ${{ secrets.SNAP_TOKEN }}
#
#      - name: Upload to snapcraft
#        if: startsWith(matrix.os, 'ubuntu')
#        run: snapcraft upload --release=stable dist/dbptk-desktop*.snap